### ISSUE TITLE
Request for Makefile, manpage

### ISSUE THREAD

**Issue by jarun** [alphapapa/bucket#2]
Could you please add the following?
Makefile: for automated installation
Manpage: usage with extensive usage examples

The tool is very useful. However, end user would definitely look for automated installation without the need of sourcing, copying files etc.

Also, a manpage with usage + all the examples you explained on GitHub readme would help for quick reference.

**Comment by alphapapa** [comment]
Sure, I'm pretty busy right now, but I'll see what I can do.  Thanks for the suggestion.

**Comment by alphapapa** [comment]
I added a man page and a Makefile for installation in https://github.com/alphapapa/bucket/commit/e678d6e97d32d1ffd8eb271f303546ae4fb4b1d3.  :)  Thanks.

**Comment by jarun** [comment]
Thank you!
